#pragma once
typedef enum assetType_e
{
	ASSET_TYPE_XMODELPIECES = 0,
	ASSET_TYPE_PHYSPRESET = 1,
	ASSET_TYPE_PHYSCONSTRAINTS = 2,
	ASSET_TYPE_DESTRUCTIBLEDEF = 3,
	ASSET_TYPE_XANIM = 4,
	ASSET_TYPE_XMODEL = 5,
	ASSET_TYPE_MATERIAL = 6,
	//ASSET_TYPE_PIXELSHADER = 7, // unused
	//ASSET_TYPE_VERTEXSHADER = 8, // unused
	ASSET_TYPE_TECHSET = 7,
	ASSET_TYPE_IMAGE = 8,
	ASSET_TYPE_SOUND = 9,
	ASSET_TYPE_LOADED_SOUND = 10,
	ASSET_TYPE_COL_MAP_SP = 11,
	ASSET_TYPE_COL_MAP_MP = 12,
	ASSET_TYPE_COM_MAP = 13,
	ASSET_TYPE_GAME_MAP_SP = 14,
	ASSET_TYPE_GAME_MAP_MP = 15,
	ASSET_TYPE_MAP_ENTS = 16,
	ASSET_TYPE_GFX_MAP = 17,
	ASSET_TYPE_LIGHTDEF = 18,
	ASSET_TYPE_UI_MAP = 19,
	ASSET_TYPE_FONT = 20,
	ASSET_TYPE_MENUFILE = 21,
	ASSET_TYPE_MENU = 22,
	ASSET_TYPE_LOCALIZE = 23,
	ASSET_TYPE_WEAPON = 24,
	ASSET_TYPE_SNDDRIVERGLOBALS = 25,
	ASSET_TYPE_FX = 26,
	ASSET_TYPE_IMPACTFX = 27,
	ASSET_TYPE_AITYPE = 28,
	ASSET_TYPE_MPTYPE = 29,
	ASSET_TYPE_CHARACTER = 30,
	ASSET_TYPE_XMODELALIAS = 31,
	ASSET_TYPE_RAWFILE = 32,
	ASSET_TYPE_STRINGTABLE = 33,
	ASSET_TYPE_PACKINDEX = 34
} assetType_t;

void* ReallocateAssetPool(assetType_t type, unsigned int newSize);